config/routes.rb
Rails.application.routes.draw do
  resources :rent_properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rent_property.rb
class RentProperty < ApplicationRecord
  validates :property_name, presence: true
  validates :rent, presence: true
  validates :address, presence: true
  validates :age, presence: true
  validates :note, presence: true
  has_many :stations, inverse_of: :rent_property, dependent: :destroy
  accepts_nested_attributes_for :stations
end

app/models/station.rb
class Station < ApplicationRecord
  validates :route_name, presence: true
  validates :walking_minutes, presence: true
  validates :station_name, presence: true
  belongs_to :rent_property, inverse_of: :stations, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rent_properties_controller.rb
class RentPropertiesController < ApplicationController
  before_action :set_rent_property, only: [:show, :edit, :update, :destroy]

  # GET /rent_properties
  # GET /rent_properties.json
  def index
    @rent_properties = RentProperty.all
  end

  # GET /rent_properties/1
  # GET /rent_properties/1.json
  def show
  end

  # GET /rent_properties/new
  def new
    @rent_property = RentProperty.new
    2.times {@rent_property.stations.build}
  end

  # GET /rent_properties/1/edit
  def edit
  end

  # POST /rent_properties
  # POST /rent_properties.json
  def create
    @rent_property = RentProperty.new(rent_property_params)
    # 親要素を保存かけてあげることで自動で子要素も保存されます！
    respond_to do |format|
      if @rent_property.save
        format.html { redirect_to @rent_property, notice: 'Rent property was successfully created.' }
        format.json { render :show, status: :created, location: @rent_property }
      else
        format.html { render :new }
        format.json { render json: @rent_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rent_properties/1
  # PATCH/PUT /rent_properties/1.json
  def update
    respond_to do |format|
      if @rent_property.update(rent_property_params)
        format.html { redirect_to @rent_property, notice: 'Rent property was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent_property }
      else
        format.html { render :edit }
        format.json { render json: @rent_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rent_properties/1
  # DELETE /rent_properties/1.json
  def destroy
    @rent_property.destroy
    respond_to do |format|
      format.html { redirect_to rent_properties_url, notice: 'Rent property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent_property
      @rent_property = RentProperty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_property_params
      params.require(:rent_property).permit(
        :property_name, :rent, :address, :age, :note,
        stations_attributes: %i(
          id _destroy rent_property_id route_name station_name walking_minutes))
      # fields_forは[引数に与えた名前]_attributesというname属性でフォームを作成する
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rent_properties_helper.rb
module RentPropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rent_properties/_form.html.erb
<%= form_for(@rent_property) do |f| %>
  <% if rent_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent_property.errors.count, "error") %> prohibited this rent_property from being saved:</h2>

      <ul>
      <% rent_property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :物件名 %><br>
    <%= f.text_field :property_name %>
    <br><br>

    <%= f.label :賃料 %><br>
    <%= f.number_field :rent %><%= "円" %>
    <br><br>

    <%= f.label :住所 %><br>
    <%= f.text_area :address %>
    <br><br>

    <%= f.label :築年数 %><br>
    <%= f.number_field :age %><%= "年" %>
    <br><br>

    <%= f.label :備考 %><br>
    <%= f.text_area :note %>
    <br><br>

    <hr>

  <% x = 1 %>
  <%= f.fields_for :stations do |df| %>
    <h3>最寄り駅<%= x %></h3>
    <%= df.label :路線名 %><br>
    <%= df.text_field :route_name %><br><br>
    <%= df.label :駅名 %><br>
    <%= df.text_field :station_name %><br><br>
    <%= df.label :徒歩分数 %><br>
    <%= df.number_field :walking_minutes %><%= "分" %><br><br>
    <% x += 1 %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rent_properties/edit.html.erb
<h1>編集</h1>
<h2>物件編集</h2>
<%= render 'form', rent_property: @rent_property %>

<%= link_to '詳細', @rent_property %> |
<%= link_to '戻る', rent_properties_path %>

app/views/rent_properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>一覧</h1>
<hr>
<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rent_properties.each do |rent_property| %>
      <tr>
        <td><%= rent_property.property_name %></td>
        <td><%= rent_property.rent.to_s(:delimited, delimiter: ',') %><%= "円" %></td>
        <td><%= rent_property.address %></td>
        <td><%= rent_property.age %><%= "年" %></td>
        <td><%= rent_property.note %></td>
        <td><%= link_to '詳細', rent_property %></td>
        <td><%= link_to '編集', edit_rent_property_path(rent_property) %></td>
        <td><%= link_to '削除', rent_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する ', new_rent_property_path %>

app/views/rent_properties/new.html.erb
<h1>登録</h1>
<h2>物件登録</h2>

<%= render 'form', rent_property: @rent_property %>
<br>
<%= link_to '戻る', rent_properties_path %>

app/views/rent_properties/show.html.erb
<h1>閲覧</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>物件名 :</strong>
  <%= @rent_property.property_name %>
</p>

<p>
  <strong>賃料 :</strong>
  <%= @rent_property.rent %>
</p>

<p>
  <strong>住所 :</strong>
  <%= @rent_property.address %>
</p>

<p>
  <strong>築年数 :</strong>
  <%= @rent_property.age %>
</p>

<p>
  <strong>備考 :</strong>
  <%= @rent_property.note %>
</p>

<br>



<p>
  <strong>路線名 :</strong>
  <%= @rent_property.stations.first.route_name %>
</p>

<p>
  <strong>駅名 :</strong>
  <%= @rent_property.stations.first.station_name %>
</p>

<p>
  <strong>徒歩分数 :</strong>
  <%= "#{@rent_property.stations.first.walking_minutes}分" %>
</p>

<br>

<p>
  <strong>路線名 :</strong>
  <%= @rent_property.stations.second.route_name %>
</p>

<p>
  <strong>駅名 :</strong>
  <%= @rent_property.stations.second.station_name %>
</p>

<p>
  <strong>徒歩分数 :</strong>
  <%= "#{@rent_property.stations.second.walking_minutes}分" %>
</p>



<%= link_to '編集', edit_rent_property_path(@rent_property) %> |
<%= link_to '戻る', rent_properties_path %>